version: '3'

services:
  app:
    build:
      context: ./node
    container_name: app
    entrypoint: dockerize -wait tcp://database:3306 -timeout 20s docker-entrypoint.sh
    command: "node index.js"
    volumes:
      - ./node:/usr/src/app
      - /usr/src/app/node_modules
    tty: true
    networks:
      - app-network
    depends_on:
      - database

  database: 
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: database
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=app_database
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - app-network

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    tty: true
    ports:
      - "8080:80"
    networks:
      - app-network
    depends_on:
      - app

networks:
  app-network:
    driver: bridge